# Site settings
title: FAQ
email: git2go@nerdishbynature.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://faq.git2go.com" # the base hostname & protocol for your site
twitter_username: git2go

# Build settings
markdown: kramdown
